services:
  - type: web
    name: crw-scraper
    runtime: docker
    repo: https://github.com/asd1054/crw-render
    plan: free
    region: oregon
    dockerfilePath: ./Dockerfile
    healthCheckPath: /health
    envVars:
      - key: PORT
        value: 3000